# Remember to add it in env.production because it is the nextjs project
apiVersion: v1
stringData:
  NEXT_PUBLIC_APP_NAME: xlog
  NEXT_PUBLIC_OUR_DOMAIN: xlog.page
  NEXT_PUBLIC_DISCORD_LINK: "https://discord.gg/46VJMMVCuF"
  NEXT_PUBLIC_TWITTER_LINK: "https://twitter.com/_xLog"
  NEXT_PUBLIC_GITHUB_LINK: "https://github.com/Crossbell-Box/xlog"
  NEXT_PUBLIC_CSB_IO: ""
  NEXT_PUBLIC_CSB_SCAN: "https://scan.crossbell.io"
  NEXT_PUBLIC_IPFS_GATEWAY: "https://ipfs.4everland.xyz/ipfs/"
  REDIS_URL: ${REDIS_URL_DEV}
kind: Secret
metadata:
  name: xlog
  namespace: crossbell
type: Opaque
---
apiVersion: v1
stringData:
  CADDY_CLUSTERING_REDIS_HOST: ${CADDY_CLUSTERING_REDIS_HOST_DEV}
  CADDY_CLUSTERING_REDIS_PORT: "6379"
  CADDY_CLUSTERING_REDIS_USERNAME: ""
  CADDY_CLUSTERING_REDIS_PASSWORD: ${CADDY_CLUSTERING_REDIS_PASSWORD_DEV}
  CADDY_CLUSTERING_REDIS_DB: "6"
  CF_API_TOKEN: ${CF_API_TOKEN}
kind: Secret
metadata:
  name: xlog-caddy
  namespace: crossbell
type: Opaque
